'use strict';
const $=id=>document.getElementById(id);
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
const labels={front_proxy:'Road-side ground proxy',front_north:'Road-side north',front_south:'Road-side south',river_side:'River-side ground',building_center:'Ground beneath footprint'};
let map,config,state={stage:36,flood:true,floodOpacity:.65,detail:'aerial',detailOpacity:1,base:'satellite'};
let floodRenderer,detailOverlay,buildingLayer,samplesLayer,contourLayer,femaLayer,extentLayer,inspectionMarker,lastClick;
const valueCache=new Map();let inspectionTimer;let preloadProgress={ready:0,total:21,failed:0};
function status(message){$('map-warning').textContent=message;$('map-warning').hidden=!message;}
async function json(file){const r=await fetch('data/'+file);if(!r.ok)throw new Error('Could not load '+file);return r.json();}
function scenario(){return config.scenarios.find(d=>d.stage===state.stage);}
function addAssetError(layer,name){layer.on('error',()=>status(name+' could not load. Please reload the page.'));return layer;}
function createFloodFrame(stage){
 const layer=L.imageOverlay(`data/flood${stage}.png`,config.bounds,{pane:'floodRaster',opacity:0,interactive:false});
 const ready=new Promise((resolve,reject)=>{
  layer.once('load',async()=>{try{await layer.getElement().decode();resolve();}catch(e){reject(e);}});
  layer.once('error',()=>reject(new Error(`Stage ${stage} image could not load`)));
 });
 layer.addTo(map);const image=layer.getElement();image.style.visibility='hidden';image.dataset.floodStage=stage;
 return{ready,show:opacity=>{layer.setOpacity(opacity);image.style.visibility='visible';},hide:()=>{image.style.visibility='hidden';},remove:()=>map.removeLayer(layer)};
}
function updateScenarioStatus(){
 const shown=floodRenderer?.displayed?.stage;
 $('map-stage').textContent=!state.flood?'Flood overlay hidden':shown===undefined?'Loading flood map…':`${shown} ft gauge scenario`;
 const pending=state.flood&&shown!==state.stage;
 $('scenario-loading').classList.toggle('pending',pending);
 $('scenario-loading').textContent=pending?(floodRenderer.failed.has(state.stage)?`Could not load ${state.stage} ft. Select it again to retry.`:`Loading ${state.stage} ft${shown===undefined?'':` · map still shows ${shown} ft`}…`):preloadProgress.ready===preloadProgress.total?'All 21 stages ready · drag to explore':`Preparing scenarios · ${preloadProgress.ready}/${preloadProgress.total} ready${preloadProgress.failed?' · unavailable stages retry on selection':''}`;
}
function drawGaugeAndHouse(diff){
 const y=236-(state.stage-32)/20*222;
 $('gauge-water').setAttribute('y',y);$('gauge-water').setAttribute('height',242-y);
 $('gauge-surface').setAttribute('d',`M2 ${y}H98`);
 $('gauge-handle').setAttribute('d',`M0 ${y-6}L9 ${y}L0 ${y+6}Z M100 ${y-6}L91 ${y}L100 ${y+6}Z`);
 $('stage').setAttribute('aria-valuetext',`${state.stage} feet at Guerneville`);
 const houseY=Math.max(5,Math.min(126,78-diff*5));
 $('house-water-fill').setAttribute('y',houseY);$('house-water-fill').setAttribute('height',132-houseY);
 $('house-water-line').setAttribute('d',`M0 ${houseY}H210`);
 $('house-water').setAttribute('aria-label',`Schematic: water ${fmt(Math.abs(diff))} feet ${diff>=0?'above':'below'} the surveyed living floor. Schematic geometry; floor reference from the 2018 certificate.`);
}
function drawChart(){const floor=config.elevation_certificate.C2b_next_higher_floor_ft,x=s=>34+(s-32)/20*279,y=z=>139-(z-30)/25*112;const pts=config.scenarios.map(d=>`${x(d.stage)},${y(d.water_elevation_ft)}`).join(' ');const ticks=[30,40,50].map(v=>`<line x1="34" x2="313" y1="${y(v)}" y2="${y(v)}" stroke="#dce6eb"/><text x="27" y="${y(v)+4}" text-anchor="end" fill="#536b77" font-size="10">${v}</text>`).join('');$('stage-chart').innerHTML=`<text x="34" y="12" fill="#536b77" font-size="10">Elevation (ft NAVD88)</text>${ticks}<line x1="34" x2="313" y1="${y(floor)}" y2="${y(floor)}" stroke="#ac7419" stroke-dasharray="5 3" stroke-width="1.5"/><polyline points="${pts}" fill="none" stroke="#087c91" stroke-width="2.5"/><circle cx="${x(state.stage)}" cy="${y(scenario().water_elevation_ft)}" r="4.5" fill="#087c91" stroke="white" stroke-width="2"/>${[32,36,40,44,48,52].map(v=>`<text x="${x(v)}" y="153" text-anchor="middle" fill="#536b77" font-size="10">${v}</text>`).join('')}<text x="175" y="169" text-anchor="middle" fill="#536b77" font-size="10">Guerneville gauge stage (ft)</text>`;
let first=config.scenarios.find(d=>d.water_elevation_ft>=floor);$('threshold').textContent=first?(first.stage===32?'Water is already above the surveyed living floor in the first mapped scenario (32 ft). Lower stages are not available.':`First available scenario above the surveyed living floor: ${first.stage} ft at Guerneville. The crossing lies between ${first.stage-1} and ${first.stage} ft in these model scenarios.`):'The surveyed living floor is above the reconstructed water surface in every available scenario (32–52 ft).';}
function updateReadouts(){const d=scenario(),floor=config.elevation_certificate.C2b_next_higher_floor_ft,diff=d.water_elevation_ft-floor;$('stage').value=state.stage;$('stage-number').textContent=state.stage;$('insurance-link').href='insurance.html?stage='+state.stage;$('water-elev').textContent=fmt(d.water_elevation_ft)+' ft';$('floor-elev').textContent=fmt(floor)+' ft';$('floor-depth').textContent=fmt(Math.abs(diff))+' ft';$('depth-label').textContent=diff>=0?'Water above living floor':'Clearance below living floor';$('floor-depth').style.color=diff>=0?'#8a471d':'#087c91';$('depth-range').textContent='2018 surveyed floor · 45.6 ft NAVD88. Water elevation remains approximate.';for(const b of document.querySelectorAll('[data-stage]'))b.classList.toggle('active',+b.dataset.stage===state.stage);$('stage-down').disabled=state.stage<=32;$('stage-up').disabled=state.stage>=52;drawGaugeAndHouse(diff);drawChart();}
async function updateFlood(){
 $('flood-legend').hidden=!state.flood;$('flood-visible').checked=state.flood;$('flood-visible-2').checked=state.flood;
 updateReadouts();
 if(!state.flood){floodRenderer.hide();updateScenarioStatus();return;}
 const selected=state.stage;const request=floodRenderer.show(selected,state.floodOpacity);updateScenarioStatus();
 try{await request;}catch{/* Keep the last good map and report the failed selection. */}
 updateScenarioStatus();
}
function setStage(s){state.stage=Math.max(32,Math.min(52,Math.round(s)));updateFlood();}
const detailInfo={aerial:{file:'aerial2025.jpg',name:'2025 aerial photography',note:'County aerial photography, about 0.25 m display sampling in the local square. Source date: 2025.'},hillshade:{file:'hillshade.png',name:'2022 lidar hillshade',note:'Bare-earth relief with trees and buildings removed. About 1 m source resolution; no vertical exaggeration used for elevation readings.'},terrain:{file:'terrain.png',name:'2022 lidar ground elevation',note:'Elevation in feet NAVD88, with hillshade. Click for the local ground elevation.',gradient:'linear-gradient(90deg,#090320,#2767a0,#48a66b,#b4b56b,#dfc9a8,#fff)',ends:['0 ft','650 ft']},canopy:{file:'canopy.png?v=20260923-2',name:'2022 canopy & object height',note:'County vegetation-height raster. May include buildings and other objects; values below 2 ft are transparent.',gradient:'linear-gradient(90deg,#e8d6a3,#c7b977,#a7ba62,#62974c,#2c713f,#124b2e)',ends:['Short · 0 ft','Tall · 200+ ft']},none:{name:'Continuous basemap',note:'Detailed raster layer hidden. Parcel, flood scenarios and optional vector layers remain available.'}};
function updateDetail(){if(detailOverlay)map.removeLayer(detailOverlay);for(const b of document.querySelectorAll('[data-detail]')){const selected=b.dataset.detail===state.detail;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected));}const d=detailInfo[state.detail];if(d.file){detailOverlay=addAssetError(L.imageOverlay('data/'+d.file,config.bounds,{pane:'detailRaster',opacity:state.detailOpacity,interactive:false}),'Detailed layer').addTo(map);}else detailOverlay=null;$('map-layer').textContent=d.name;$('detail-note').textContent=d.note;$('detail-legend').innerHTML=d.gradient?`<div class="gradient" style="background:${d.gradient}"></div><div class="ends"><span>${d.ends[0]}</span><span>${d.ends[1]}</span></div>`:'';}
function toggle(layer,on){if(on)layer.addTo(map);else map.removeLayer(layer);}
function loadValues(name){if(!valueCache.has(name)){valueCache.set(name,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0);resolve({data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height});};im.onerror=()=>{valueCache.delete(name);reject(new Error('Cannot load elevation samples'));};im.src='data/'+name+'-values.png';}));}return valueCache.get(name);}
function sample(grid,p){const xy=L.CRS.EPSG3857.project(p),b=config.bbox3857;if(xy.x<b[0]||xy.x>=b[2]||xy.y<=b[1]||xy.y>b[3])return null;const x=Math.floor((xy.x-b[0])/(b[2]-b[0])*grid.width),y=Math.floor((b[3]-xy.y)/(b[3]-b[1])*grid.height),i=(y*grid.width+x)*4;if(!grid.data[i+3])return null;return(grid.data[i]*256+grid.data[i+1])/100;}
let inspectVersion=0;
async function inspect(p,pan=true){
// A stage refresh never creates, reopens, or pans a popup the user dismissed.
if(!pan&&(!inspectionMarker||!inspectionMarker.isPopupOpen()))return;
const version=++inspectVersion,lastStage=state.stage;lastClick=p;
if(pan){if(inspectionMarker)map.removeLayer(inspectionMarker);inspectionMarker=L.circleMarker(p,{radius:4,color:'#fff',weight:2,fillColor:'#142c37',fillOpacity:1,pane:'markers'}).addTo(map);inspectionMarker.bindPopup('Reading local layers…',{autoPan:true}).openPopup();inspectionMarker.on('popupopen',()=>inspect(p,false));}
const marker=inspectionMarker;if(!pan)marker.getPopup().options.autoPan=false;
try{const grids=await Promise.all(['dem2022','surfaceheight',`flood${lastStage}`].map(loadValues));if(version!==inspectVersion)return;const a=grids.map(g=>sample(g,p));if(a[0]===null){marker.setPopupContent('<h3>Outside study square</h3>Local lidar and flood rasters stop at the dashed boundary. The continuous basemap remains available.');return;}marker.setPopupContent(`<h3>Terrain & flood sample</h3><table><tr><td>2022 ground elevation</td><td>${fmt(a[0])} ft</td></tr><tr><td>Canopy / object height</td><td>${fmt(a[1])} ft</td></tr><tr><td>Depth at ${lastStage}-ft stage</td><td>${a[2]>0?fmt(a[2])+' ft':'Not mapped'}</td></tr></table><small>Ground: NAVD88. Flood depth: above model ground, not the floor. ${a[2]>0?'':'A zero raster cell can mean no mapped inundation or no data.'}</small>`);}catch(e){if(version===inspectVersion)marker.setPopupContent('Sample data could not load. Try again.');}}
async function init(){config=await json('config.json?v=20260923-6');const [parcel,buildings,fema,contours]=await Promise.all(['parcel.json','buildings.json','fema.json','contours.json'].map(json));map=L.map('map',{zoomControl:false,maxZoom:22,minZoom:3,zoomSnap:.5}).setView(config.center,18);L.control.zoom({position:'topright'}).addTo(map);L.control.scale({position:'bottomright',imperial:true,metric:true,maxWidth:100}).addTo(map);for(const [n,z] of [['detailRaster',250],['fema',310],['floodRaster',350],['contours',390],['vectors',410],['markers',450]]){map.createPane(n);map.getPane(n).style.zIndex=z;}map.attributionControl.addAttribution('Local data: County of Sonoma / QSI / NV5 · FEMA');const baseLayers={satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:19,maxZoom:22,attribution:'Imagery © Esri, Maxar, Earthstar Geographics'}),streets:L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxNativeZoom:19,maxZoom:22,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}),topo:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:19,maxZoom:22,attribution:'Topo © Esri and contributors'})};let activeBase=baseLayers.satellite.addTo(map);for(const l of Object.values(baseLayers))l.on('tileerror',()=>status('Some basemap tiles could not load. Local study layers are still available.'));function setBase(name){map.removeLayer(activeBase);state.base=name;activeBase=baseLayers[name].addTo(map);for(const b of document.querySelectorAll('[data-base]'))b.classList.toggle('active',b.dataset.base===name);status('');}
L.geoJSON(parcel,{pane:'vectors',style:{color:'#ffcf55',weight:3,fill:false}}).addTo(map).bindTooltip('Study parcel · 21008 River Blvd',{sticky:true});buildingLayer=L.geoJSON(buildings,{pane:'vectors',style:f=>({color:f.properties.OBJECTID===config.building_id?'#fff':'#cad9df',weight:f.properties.OBJECTID===config.building_id?2:1,fillColor:'#18384a',fillOpacity:.08}),onEachFeature:(f,l)=>l.on('click',e=>inspect(e.latlng))}).addTo(map);const house=L.circleMarker(config.center,{pane:'markers',radius:4,color:'#ffcf55',fillColor:'#112a36',fillOpacity:1,weight:2}).addTo(map);house.bindTooltip('21008 River Blvd',{permanent:true,direction:'top',offset:[0,-10],className:'house-label'});house.on('click',e=>inspect(e.latlng));extentLayer=L.rectangle(config.bounds,{pane:'vectors',color:'#f5d071',weight:1.5,dashArray:'6 6',fill:false,interactive:false}).addTo(map);samplesLayer=L.layerGroup(config.points.map(p=>L.circleMarker([p.lat,p.lon],{pane:'markers',radius:5,weight:2,color:'#804600',fillColor:'#ffd475',fillOpacity:1}).bindTooltip(labels[p.id],{direction:'top',className:'sample-label'}).bindPopup(`<h3>${labels[p.id]}</h3><table><tr><td>2013 ground</td><td>${fmt(p.dem2013)} ft</td></tr><tr><td>2022 ground</td><td>${fmt(p.dem2022)} ft</td></tr></table><small>Approximate sample location. NAVD88 feet; no measured floor or door elevation.</small>`)));
contourLayer=L.geoJSON(contours,{pane:'contours',style:f=>({color:'#222e24',weight:f.properties.elevation_ft%50===0?1.3:.6,opacity:.65}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.elevation_ft+' ft NAVD88',{sticky:true})});femaLayer=L.geoJSON(fema,{pane:'fema',style:f=>{const p=f.properties,c=p.ZONE_SUBTY==='FLOODWAY'?'#a258db':p.SFHA_TF==='T'?'#e58438':'#d1ad42';return{color:c,weight:1.5,fillColor:c,fillOpacity:p.FLD_ZONE==='X'&&!String(p.ZONE_SUBTY).includes('0.2')?0:.22};},onEachFeature:(f,l)=>{const p=f.properties;l.bindPopup(`<h3>FEMA ${p.FLD_ZONE}</h3>${p.ZONE_SUBTY||'Mapped flood zone'}<small>Effective map panel at property: July 31, 2024. This zone does not specify the chance of water entering the living floor.</small>`);}});
$('depth-colors').innerHTML=config.depth_colors.map(c=>`<i style="background:${c}"></i>`).join('');$('depth-labels').innerHTML=config.depth_labels.map(c=>`<span>${c}</span>`).join('');$('gauge-ticks').innerHTML=Array.from({length:21},(_,i)=>{const stage=32+i,y=236-i/20*222;return `<path d="M21 ${y}H${stage%2===0?38:30}" stroke="#253d48" stroke-width="${stage%2===0?2:1}"/>${stage%4===0?`<text x="49" y="${y+4}" font-size="12" fill="#253d48" font-weight="650">${stage}</text>`:''}`;}).join('');
floodRenderer=new FloodScenarios({stages:config.scenarios.map(d=>d.stage),createFrame:createFloodFrame,onProgress:p=>{preloadProgress=p;updateScenarioStatus();},onDisplay:stage=>{updateScenarioStatus();if(stage!==null){floodRenderer.setOpacity(state.floodOpacity);clearTimeout(inspectionTimer);if(lastClick)inspectionTimer=setTimeout(()=>inspect(lastClick,false),140);}}});
updateDetail();updateFlood().then(()=>floodRenderer.preload(state.stage));map.on('click',e=>inspect(e.latlng));
for(const b of document.querySelectorAll('[data-stage]'))b.onclick=()=>setStage(+b.dataset.stage);for(const b of document.querySelectorAll('[data-base]'))b.onclick=()=>setBase(b.dataset.base);$('stage').oninput=e=>setStage(+e.target.value);$('stage-down').onclick=()=>setStage(state.stage-1);$('stage-up').onclick=()=>setStage(state.stage+1);for(const id of ['flood-visible','flood-visible-2'])$(id).onchange=e=>{state.flood=e.target.checked;updateFlood();};$('flood-opacity').oninput=e=>{state.floodOpacity=+e.target.value/100;$('flood-opacity-label').textContent=e.target.value+'%';floodRenderer.setOpacity(state.floodOpacity);};for(const b of document.querySelectorAll('[data-detail]'))b.onclick=()=>{state.detail=b.dataset.detail;updateDetail();};$('detail-opacity').oninput=e=>{state.detailOpacity=+e.target.value/100;$('detail-opacity-label').textContent=e.target.value+'%';if(detailOverlay)detailOverlay.setOpacity(state.detailOpacity);};for(const [id,l] of [['contours-visible',contourLayer],['buildings-visible',buildingLayer],['samples-visible',samplesLayer],['extent-visible',extentLayer],['fema-visible',femaLayer]])$(id).onchange=e=>toggle(l,e.target.checked);$('show-points').onclick=()=>{$('samples-visible').checked=true;samplesLayer.addTo(map);focusMap(config.center,20);};$('home-view').onclick=()=>focusMap(config.center,20);$('study-view').onclick=()=>map.fitBounds(config.bounds,{paddingTopLeft:[35,35],paddingBottomRight:[35+paletteInset(),35]});$('region-view').onclick=()=>focusMap([38.475,-122.997],13);$('mobile-toggle').onclick=()=>{$('floor-dialog').append(document.querySelector('.secondary-controls'));$('floor-dialog').showModal();};$('floor-close').onclick=()=>$('floor-dialog').close();$('floor-dialog').addEventListener('close',()=>document.querySelector('aside').append(document.querySelector('.secondary-controls')));
window.addEventListener('resize',()=>{if(innerWidth>640&&$('floor-dialog').open)$('floor-dialog').close();map.invalidateSize();});
function paletteInset(){return window.matchMedia('(min-width: 641px)').matches&&!$('panel-layers').hidden?$('layer-palette').offsetWidth+24:0;}
function focusMap(center,zoom){const p=map.project(center,zoom);p.x+=paletteInset()/2;map.setView(map.unproject(p,zoom),zoom);}
function setLayersOpen(open){const before=paletteInset();$('panel-layers').hidden=!open;$('layers-toggle').setAttribute('aria-expanded',String(open));$('layer-palette').classList.toggle('collapsed',!open);$('layers-toggle').querySelector('.palette-chevron').textContent=open?'−':'+';map.panBy([(paletteInset()-before)/2,0],{animate:false});}
setLayersOpen(!window.matchMedia('(max-width: 640px)').matches);focusMap(config.center,18);
$('layers-toggle').onclick=()=>setLayersOpen($('panel-layers').hidden);
$('sources-open').onclick=()=>$('sources-dialog').showModal();
$('sources-close').onclick=()=>$('sources-dialog').close();
$('sources-dialog').addEventListener('click',e=>{if(e.target===$('sources-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
window.atlas={map,state,config,setStage,setBase,inspect,toggle};}
init().catch(e=>{$('fatal').hidden=false;$('fatal').textContent='The atlas could not load: '+e.message+'. Please reload.';console.error(e);});
