'use strict';
const $=id=>document.getElementById(id),M=InsuranceModel;
const money=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
const pct=x=>(100*x).toFixed(1)+'%';
let config,historyData,stage=45,current,annualResult;
const key='russian-river-insurance-assumptions-v1';
function read(){const number=id=>$(id).value.trim()===''?NaN:Number($(id).value);return{deductible:number('deductible'),limit:number('limit'),premium:$('premium').value.trim()===''?null:number('premium'),waterOffset:number('waterOffset'),costScale:number('costScale'),lowerMax:number('lowerMax'),lowerEligible:number('lowerEligible'),upperEligible:number('upperEligible'),repairs:[0,1,2,3,4].map(i=>number('repair-'+i)),weights:[0,1,2,3,4].map(i=>number('weight-'+i))};}
function set(a){for(const k of ['deductible','limit','premium','waterOffset','costScale','lowerMax','lowerEligible','upperEligible'])$(k).value=a[k]===null?'':a[k];a.repairs.forEach((v,i)=>$('repair-'+i).value=v);a.weights.forEach((v,i)=>$('weight-'+i).value=v);}
function renderHistory(){
 const only=$('enso-only').checked, period=historyData.periods['1984'], stats=only?period.el_nino:period.all;
 const count=`${stats.k} of ${stats.n} ${only?'El Niño winters':'years'} (${Math.round(stats.fraction*100)}%)`;
 $('history-stat').textContent=`${count} reached or exceeded the 2019 peak of 72,000 cfs.`;
 $('enso-interpretation').textContent=only?`Other winters: ${period.other.k} of ${period.other.n} (${Math.round(period.other.fraction*100)}%). The small samples do not establish an El Niño increase in large-flood frequency. Faint marks show the other winters.`:'Large floods occurred in both El Niño and other winters. Select the filter to inspect the El Niño subset.';
 const range=s=>s.interval_95.map(x=>Math.round(x*100)+'%').join('–');
 $('history-intervals').textContent=`95% binomial intervals: all years ${range(period.all)}; El Niño ${range(period.el_nino)}; other winters ${range(period.other)}. These describe sampling uncertainty assuming independent years with constant probability, not future climate or model error. Full-record threshold count: ${historyData.periods['1940'].all.k} of 86 years.`;
 const rows=historyData.annual_peaks.filter(x=>x.water_year>=1984), w=Math.max(300,Math.round($('history-chart').getBoundingClientRect().width)),h=215,left=48,right=14,top=20,bottom=35;
 const x=y=>left+(y-1984)/(2025-1984)*(w-left-right), y=q=>h-bottom-q/110000*(h-top-bottom);
 const grid=[0,50000,100000].map(q=>`<line x1="${left}" x2="${w-right}" y1="${y(q)}" y2="${y(q)}" stroke="#dce4df"/><text x="${left-8}" y="${y(q)+4}" text-anchor="end">${q/1000}k</text>`).join('');
 const marks=rows.map(r=>{const selected=!only||r.el_nino_winter,color=selected?(only?'#9b651c':'#147879'):'#bdc9c5';return `<g opacity="${selected?1:.4}"><title>Water year ${r.water_year}: ${r.peak_cfs.toLocaleString('en-US')} cfs; ${r.el_nino_winter?'El Niño':'other'} winter</title><line x1="${x(r.water_year)}" x2="${x(r.water_year)}" y1="${y(0)}" y2="${y(r.peak_cfs)}" stroke="${color}" stroke-width="2"/><circle cx="${x(r.water_year)}" cy="${y(r.peak_cfs)}" r="3" fill="${color}"/></g>`;}).join('');
 const axis=(w<450?[1984,2005,2025]:[1984,1995,2005,2015,2025]).map(yr=>`<text x="${x(yr)}" y="${h-14}" text-anchor="middle">${yr}</text>`).join('');
 $('history-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="flow-chart-title flow-chart-desc"><title id="flow-chart-title">Annual peak river discharge, 1984–2025</title><desc id="flow-chart-desc">${count} reached 72,000 cfs. ${only?'El Niño winters are highlighted; other winters are faded.':''}The full record is available as CSV in Data, full record, and model basis.</desc><g font-family="system-ui,sans-serif" font-size="12" fill="#536971">${grid}${marks}<line x1="${left}" x2="${w-right}" y1="${y(72000)}" y2="${y(72000)}" stroke="#a76c21" stroke-dasharray="5 4"/><text x="${w-right}" y="${y(72000)-7}" text-anchor="end" fill="#8b5918">2019 peak · 72,000 cfs</text>${axis}<text x="${left}" y="12">cfs</text></g></svg>`;
}
async function loadHistory(){
 try{const response=await fetch('data/research/flood_enso_history.json?v=1');if(!response.ok)throw new Error('History data unavailable');historyData=await response.json();$('enso-only').disabled=false;$('enso-only').onchange=renderHistory;window.addEventListener('resize',renderHistory);renderHistory();}
 catch{$('history-stat').textContent='The historical record could not be loaded. Reload the page or open the research page.';}
}
// Keep the homeowner view about event protection, not invented annual odds.
function renderBrief(){
 const rounded=x=>x===0?'$0':'~'+new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:2}).format(x);
 const major=M.event(current,config,50);
 $('decision-conclusion').textContent=major.payout>0?`Insurance is worth considering if a ${rounded(major.loss).replace('~','')} repair bill would be difficult to absorb. In the larger flood example, it reduces owner-paid repairs to about ${rounded(major.retained).replace('~','')}. ${current.premium===null?'The annual premium is still needed to assess the policy’s value.':'At '+money(current.premium)+' per year, cost-effectiveness remains unresolved; property damage probabilities and coverage still need verification.'}`:'Under the entered assumptions, insurance pays nothing in the larger flood example. These assumptions do not support buying this policy for that event; verify its coverage and deductible.';
 if(major.payout>0&&major.payout<major.loss/2)$('decision-conclusion').textContent=`Under these assumptions, most of the larger flood’s repair cost remains with the owner: ${rounded(major.retained)} of ${rounded(major.loss)}. The policy offers limited protection in this example; its price and coverage need review before purchase.`;
 $('brief-limit').textContent=money(current.limit);$('brief-deductible').textContent=money(current.deductible);
 $('simple-examples').innerHTML=[40,50].map((s,i)=>{
  const e=M.event(current,config,s);
  const title=e.depth>0?'Water reaches living areas':e.lowerDepth>0?'Water under the house':'Water stays below both floors';
  return `<div class="example-card"><span class="example-label">${s} ft at Guerneville</span><h3>${title}</h3><div class="comparison"><div><span>Without insurance</span><strong>${rounded(e.loss)}</strong></div><div class="insured"><span>With insurance</span><strong>${rounded(e.retained)}</strong></div></div></div>`;
 }).join('');
 $('simple-premium').textContent=current.premium===null?'No premium has been entered.':`${money(current.premium)} per year, in addition to owner-paid repairs.`;
}
function render(){
 current=read();const errors=M.validate(current);$('simple-examples').hidden=!!errors.length;$('error').hidden=!errors.length;$('error').textContent=errors.join(' ');for(const id of ['export','print','save'])$(id).disabled=!!errors.length;
 $('waterOffset-value').textContent=(current.waterOffset>0?'+':'')+current.waterOffset.toFixed(2)+' ft';$('costScale-value').textContent=current.costScale.toFixed(2)+'×';
 if(errors.length){$('decision-conclusion').textContent='The assessment is unavailable until the input error below is corrected.';$('brief-limit').textContent='—';$('brief-deductible').textContent='—';$('simple-premium').textContent='Check the input error above.';for(const id of ['event-loss','event-payout','event-retained','annual-loss','annual-payout','annual-retained','claim-probability','ten-year'])$(id).textContent='—';$('event-water').textContent='Fix the highlighted assumptions to calculate.';$('event-breakdown').textContent='';$('event-bar').innerHTML='';$('premium-conclusion').textContent='Results unavailable until the assumptions are valid.';$('remaining').textContent='';$('sensitivity-rows').innerHTML='';for(let i=0;i<5;i++){$('loss-'+i).textContent='—';$('payout-'+i).textContent='—';}annualResult=null;return;}
 renderBrief();annualResult=M.annual(current,config);const e=M.event(current,config,stage);$('event-stage-number').textContent=stage;
 $('event-water').textContent=`Water here: ${e.water.toFixed(1)} ft NAVD88 · ${Math.abs(e.depth).toFixed(1)} ft ${e.depth>0?'above':'below'} the ${config.elevation_certificate.C2b_next_higher_floor_ft.toFixed(1)}-ft living-floor reference.`;
 $('event-loss').textContent=money(e.loss);$('event-payout').textContent=money(e.payout);$('event-retained').textContent=money(e.retained);$('event-bar').innerHTML=`<span style="width:${e.loss?100*e.payout/e.loss:0}%"></span>`;
 $('event-breakdown').textContent=`Downstairs ${money(e.lower)} + above-floor repairs ${money(e.upper)}. Eligible loss ${money(e.eligible)}; deductible ${money(current.deductible)}. Teal is the insurer’s share; gray is retained loss. Premium is separate.`;
 annualResult.events.forEach((x,i)=>{$('loss-'+i).textContent=money(x.loss);$('payout-'+i).textContent=money(x.payout);});
 $('remaining').textContent=`Entered flood scenarios total ${pct(annualResult.totalWeight)} per year. The remaining ${pct(1-annualResult.totalWeight)} is assigned zero modeled damage. Floods below, between, and above these representative scenarios are not separately integrated.`;
 $('annual-loss').textContent=money(annualResult.loss);$('annual-payout').textContent=money(annualResult.payout);$('annual-retained').textContent=money(annualResult.retained);$('claim-probability').textContent=pct(annualResult.claimProbability);$('ten-year').textContent=pct(annualResult.tenYearProbability);
 $('premium-conclusion').textContent=current.premium===null?`Premium unknown. Under these assumptions, the policy transfers an average ${money(annualResult.payout)} of modeled losses per year. Enter a premium to compare annual cash costs.`:`With a ${money(current.premium)} annual premium: average modeled annual cost is ${money(annualResult.costWithInsurance)} with insurance (premium + retained loss), versus ${money(annualResult.loss)} without insurance. Premium ${current.premium<=annualResult.payout?'is below or equal to':'exceeds'} modeled average payout by ${money(Math.abs(current.premium-annualResult.payout))}. This does not measure the value of avoiding a severe loss.`;
 $('sensitivity-rows').innerHTML=M.sensitivity(current,config).map(c=>`<tr><td>${c.name}</td><td>${money(c.result.payout)}</td><td>${pct(c.result.claimProbability)}</td><td>${c.actualOffset.toFixed(2)} ft / ${c.actualCost.toFixed(2)}× / ${c.frequency.toFixed(2)}×</td></tr>`).join('');
 $('print-assumptions').textContent=`ILLUSTRATIVE STRESS TEST · not calibrated annual risk. Surveyed living floor ${config.elevation_certificate.C2b_next_higher_floor_ft} ft NAVD88; lower enclosure ${config.elevation_certificate.C2a_bottom_enclosure_floor_ft} ft. Deductible ${money(current.deductible)}; limit ${money(current.limit)}; premium ${current.premium===null?'unknown':money(current.premium)}. Water offset ${current.waterOffset} ft; cost multiplier ${current.costScale}×. Downstairs allowance ${money(current.lowerMax)}, ${current.lowerEligible}% eligible; upstairs ${current.upperEligible}% eligible. Upstairs costs at first wetting / 1 / 3 / 6 / 10 ft: ${current.repairs.map(money).join(' / ')}. Probability inputs are assumptions; other years receive zero loss. One event per year; repeated floods and unrepresented extremes excluded. Sensitivity rows are not confidence intervals.`;
}
async function init(){
 $('assumption-panel').open=true;
 const response=await fetch('data/config.json?v=20260923-6');if(!response.ok)throw new Error('Could not load certificate and scenario data.');config=await response.json();
 $('survey-floor').textContent=config.elevation_certificate.C2b_next_higher_floor_ft+' ft';$('survey-lower').textContent=config.elevation_certificate.C2a_bottom_enclosure_floor_ft+' ft';
 $('probability-rows').innerHTML=M.stages.map((s,i)=>`<tr><td>${s} ft${s===45?' · near 2019 crest':''}</td><td><label class="sr-only" for="weight-${i}">Annual scenario probability at ${s} ft, percent</label><input id="weight-${i}" data-input type="number" min="0" max="100" step="0.5" value="${M.defaults.weights[i]}"></td><td id="loss-${i}">—</td><td id="payout-${i}">—</td></tr>`).join('');
 const print=document.createElement('p');print.id='print-assumptions';print.className='print-only';document.querySelector('#technical-details').append(print);
 set(M.defaults);try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.schema===1&&saved.assumptions&&M.validate(saved.assumptions).length===0){set(saved.assumptions);$('save-status').textContent='Loaded assumptions saved in this browser.';}}catch{$('save-status').textContent='Saved assumptions unavailable; using defaults.';}
 const selected=Number(new URLSearchParams(location.search).get('stage'));if(Number.isInteger(selected)&&selected>=32&&selected<=52)stage=selected;$('event-stage').value=stage;
 for(const input of document.querySelectorAll('[data-input]'))input.addEventListener('input',()=>{render();$('save-status').textContent='Unsaved changes · calculated locally.';});
 $('event-stage').oninput=e=>{stage=Number(e.target.value);render();};
 $('save').onclick=()=>{try{localStorage.setItem(key,JSON.stringify({schema:1,assumptions:current}));$('save-status').textContent='Saved on this browser/device.';}catch{$('save-status').textContent='Browser storage unavailable. Use the download instead.';}};
 $('reset').onclick=()=>{try{localStorage.removeItem(key);}catch{}set(M.defaults);render();$('save-status').textContent='Illustrative defaults restored; saved inputs removed.';};
 $('export').onclick=()=>{const record={schema:1,created:new Date().toISOString(),status:'Illustrative editable assumptions; not calibrated property risk or verified policy terms',assumptions:current,certificate:config.elevation_certificate,selectedStage:stage,selectedEvent:M.event(current,config,stage),annual:annualResult,sensitivity:M.sensitivity(current,config),method:'Five mutually exclusive annual-maximum flood scenarios; remaining probability assigned zero loss. One building deductible; no contents, inflation or repeated-event losses. Lower loss saturates at3ft; upper cost curve at10ft. Probability inputs are not observed frequencies.'};$('export-text').value=JSON.stringify(record,null,2)+'\n';$('export-status').textContent='';$('export-dialog').showModal();};
 $('export-close').onclick=()=>$('export-dialog').close();
 $('export-download').onclick=()=>{const url=URL.createObjectURL(new Blob([$('export-text').value],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='russian-river-insurance-scenario.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);$('export-status').textContent='Download requested. Copy JSON is available if your browser does not save the file.';};
 $('export-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('export-text').value);$('export-status').textContent='Copied scenario JSON.';}catch{$('export-text').focus();$('export-text').select();$('export-status').textContent='Text selected. Use your device’s Copy command.';}};
 $('print').onclick=()=>window.print();render();loadHistory();
}
init().catch(e=>{$('decision-conclusion').textContent='The assessment could not be loaded.';$('home-brief').hidden=true;$('error').hidden=false;$('error').textContent=e.message;for(const id of ['export','print','save'])$(id).disabled=true;});
