import * as THREE from './vendor/three/three.module.js';
// A procedural field companion. Never writes to the scientific layers or exports.
export function createBill({scene,pits,heightAt,origin,camera,controls,project,host,render,stations,explore}){
 const $=s=>document.querySelector(s),root=new THREE.Group(),overlay=new THREE.Scene();overlay.add(root);root.visible=false;for(const light of scene.children.filter(o=>o.isLight))overlay.add(light.clone());
 const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:1});
 const blue=mat('#284c85'),red=mat('#ae263c'),skin=mat('#dfb18e'),gray=mat('#bcb9ae'),dark=mat('#242d34'),brown=mat('#655346'),paper=mat('#e5e0c7');
 function part(g,geo,m,x,y,z){const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);g.add(o);return o;}
 const box=(g,m,x,y,z,w,h,d)=>part(g,new THREE.BoxGeometry(w,h,d),m,x,y,z);
 const ball=(g,m,x,y,z,r,sx=1,sy=1,sz=1)=>{const o=part(g,new THREE.SphereGeometry(r,14,10),m,x,y,z);o.scale.set(sx,sy,sz);return o;};
 const torso=box(root,blue,0,1.16,0,.45,.64,.24);const sweater=box(root,red,0,1.16,0,.47,.65,.26);sweater.visible=false;
 const legs=[],arms=[];for(const side of [-1,1]){const leg=new THREE.Group();leg.position.set(side*.125,.84,0);root.add(leg);box(leg,dark,0,-.36,0,.17,.69,.18);box(leg,brown,0,-.76,.055,.19,.13,.31);legs.push(leg);const arm=new THREE.Group();arm.position.set(side*.29,1.41,0);root.add(arm);const sleeve=box(arm,blue,0,-.23,0,.16,.45,.18);ball(arm,skin,0,-.49,0,.095);arms.push({pivot:arm,sleeve});}
 ball(root,skin,0,1.64,.015,.205,.9,1.08,.95);ball(root,gray,0,1.64,-.06,.21,1,1,.8);ball(root,skin,0,1.66,.085,.18,.92,1, .8);ball(root,skin,0,1.65,.235,.046,1,1,1.3);
 // Dark glasses, silver moustache, and a striped knit cap.
 for(const x of [-.087,.087])box(root,dark,x,1.735,.218,.14,.058,.035);box(root,dark,0,1.735,.215,.045,.018,.03);ball(root,gray,0,1.59,.223,.08,1,.3,.35);
 const knit=new THREE.Group();root.add(knit);const capColors=['#69524c','#b0816a','#546768','#94715a','#66524d'];for(let i=0;i<5;i++){const radius=.21-i*.018;part(knit,new THREE.CylinderGeometry(radius-.014,radius,.052,16),mat(capColors[i]),0,1.82+i*.05,0);}ball(knit,brown,0,2.057,0,.065,1,.65,1);
 const summer=new THREE.Group();root.add(summer);summer.visible=false;const teal=mat('#408d9d'),linen=mat('#dadbd0');ball(summer,teal,0,1.88,-.005,.213,1,.65,1);box(summer,teal,0,1.835,.2,.4,.025,.28);box(summer,dark,0,1.17,-.245,.41,.52,.19);for(const x of [-.18,.18])box(summer,dark,x,1.26,.145,.055,.48,.035);for(const x of [-.115,.115])box(summer,linen,x,1.23,.14,.14,.14,.02);
 const rain=new THREE.Group();root.add(rain);const yellow=mat('#edc52d');box(rain,yellow,0,1.07,0,.5,.86,.3);ball(rain,yellow,0,1.74,-.105,.255,1.06,1.33,.77);box(rain,mat('#e2b327'),0,1.86,.12,.48,.065,.29);for(let i=0;i<4;i++)ball(rain,brown,0,1.3-i*.14,.161,.015);
 const draped=new THREE.Group();root.add(draped);box(draped,red,0,1.38,-.17,.54,.46,.07);box(draped,red,0,1.48,0,.6,.15,.31);for(const side of [-1,1]){const sleeve=box(draped,red,side*.14,1.15,.18,.13,.59,.075);sleeve.rotation.z=side*.12;}ball(draped,red,0,1.41,.22,.075,1.5,.7,.8);
 // A few frayed yarn ends distinguish the old sweater from a pristine uniform.
 for(let i=0;i<5;i++)box(draped,red,(i-2)*.09,1.13-.025*(i%2),-.17,.012,.08,.018);
 const notebook=box(arms[0].pivot,brown,0,-.47,.14,.25,.035,.32);box(notebook,paper,0,.022,0,.23,.008,.29);
 const rod=part(arms[1].pivot,new THREE.CylinderGeometry(.013,.013,1.13,6),mat('#d8b16c'),0,-.38,.12);
 const shovel=new THREE.Group();arms[1].pivot.add(shovel);shovel.visible=false;part(shovel,new THREE.CylinderGeometry(.018,.018,.95,8),brown,0,-.35,.12);box(shovel,mat('#a8b1b2'),0,-.88,.13,.19,.24,.035);box(shovel,brown,0,.15,.12,.15,.035,.035);
 const halo=part(root,new THREE.RingGeometry(.5,.6,32),new THREE.MeshBasicMaterial({color:'#edc889',side:THREE.DoubleSide,transparent:true,opacity:.65,depthWrite:false}),0,.04,0);halo.rotation.x=-Math.PI/2;
 let season='wet';function outfit(){const dry=season==='dry',wet=season==='wet';knit.visible=season==='sweater';summer.visible=dry;rain.visible=wet;sweater.visible=season==='sweater'&&wearing;draped.visible=season==='sweater'&&!wearing;torso.material=dry?linen:blue;arms.forEach(a=>a.sleeve.material=wet?yellow:dry?linen:wearing?red:blue);legs.forEach(l=>l.children[0].material=dry?linen:dark);host.parentElement.dataset.billSeason=season;}
 $('#bill-season').onchange=e=>{season=e.target.value;outfit();render();};
 let digging=null,digElapsed=0,wasPaused=false,notice='',noticeTime=0;
 let enabled=false,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,follow=true,elapsed=0,station=0,dwell=0,visits=0,pose='Walking',wearing=false;
 const route=stations.length?stations:[{x:15,z:0,label:'the hillslope'}];root.position.set(route[0].x,heightAt(route[0].x+origin[0],origin[1]-route[0].z)-origin[2],route[0].z);station=route.length>1?1:0;
 const label=document.createElement('div');label.id='bill-label';label.hidden=true;label.textContent='Bill';host.parentElement.append(label);
 function status(){const text=noticeTime>0?notice:digging?(paused?'Dig paused':`Digging a soil pit · ${Math.min(99,Math.floor(digElapsed/4.2*100))}%`):paused?'Field break':pose==='Walking'?`Walking to ${route[station].label}`:`${pose} · stop ${visits}`;$('#bill-status').textContent=text;host.parentElement.dataset.billState=text;host.parentElement.dataset.billPosition=root.position.toArray().map(x=>x.toFixed(2)).join(',');}
 function finishDig(){if(!digging)return;pits.progress(digging,1);digging=null;shovel.visible=false;rod.visible=true;notebook.visible=true;root.rotation.x=0;arms[0].pivot.rotation.x=-.85;arms[1].pivot.rotation.x=0;paused=wasPaused;$('#bill-dig').disabled=false;$('#bill-dig').textContent='Dig a pit';$('#bill-pause').setAttribute('aria-pressed',String(paused));$('#bill-pause').textContent=paused?'Resume':'Pause';status();}
 $('#bill-dig').onclick=()=>{if(digging)return;const x=root.position.x+Math.sin(root.rotation.y)*1.05,z=root.position.z+Math.cos(root.rotation.y)*1.05;digging=pits.begin(x,z);if(!digging){notice='A pit is already here — let Bill walk a little farther.';noticeTime=3;status();return;}noticeTime=0;wasPaused=paused;paused=false;digElapsed=0;shovel.visible=true;rod.visible=false;notebook.visible=false;$('#bill-dig').disabled=true;$('#bill-dig').textContent='Digging…';$('#bill-pause').setAttribute('aria-pressed','false');$('#bill-pause').textContent='Pause';if(matchMedia('(prefers-reduced-motion: reduce)').matches)finishDig();status();render();};
 $('#bill-clear-pits').onclick=()=>{finishDig();pits.clear();render();};
 function clearTerrain(){camera.position.y=Math.max(camera.position.y,heightAt(camera.position.x+origin[0],origin[1]-camera.position.z)-origin[2]+4);}
 function releaseFollow(){follow=false;$('#bill-follow').setAttribute('aria-pressed','false');}
 function focus(){controls.target.copy(root.position).add(new THREE.Vector3(0,1,0));camera.position.copy(controls.target).add(new THREE.Vector3(9,12,11));clearTerrain();controls.update();}
 function toggle(){outfit();enabled=!enabled;if(!enabled)finishDig();root.visible=enabled;label.hidden=!enabled;$('#bill-toggle').setAttribute('aria-pressed',String(enabled));$('#bill-panel').hidden=!enabled;if(enabled){controls.autoRotate=false;$('#scene-spin').setAttribute('aria-pressed','false');$('#bill-pause').setAttribute('aria-pressed',String(paused));$('#bill-pause').textContent=paused?'Resume':'Pause';follow=true;$('#bill-follow').setAttribute('aria-pressed','true');focus();}status();render();}
 $('#bill-toggle').onclick=toggle;$('#bill-pause').onclick=()=>{paused=!paused;$('#bill-pause').setAttribute('aria-pressed',String(paused));$('#bill-pause').textContent=paused?'Resume':'Pause';status();};$('#bill-follow').onclick=()=>{follow=!follow;$('#bill-follow').setAttribute('aria-pressed',String(follow));if(follow)focus();};
 $('#bill-roam').onclick=()=>{releaseFollow();explore();};
 // Manual camera navigation remains available; following can be restored explicitly.
 controls.addEventListener('start',()=>{if(enabled)releaseFollow();});
 function update(dt){if(!enabled)return false;noticeTime=Math.max(0,noticeTime-dt);const old=root.position.clone();if(!paused){elapsed+=dt;if(digging){digElapsed+=dt;const t=Math.min(1,digElapsed/4.2),stroke=Math.sin(digElapsed*Math.PI*2.4);pits.progress(digging,t);root.rotation.x=.12+.12*stroke;root.rotation.z=0;arms[0].pivot.rotation.x=-.5-.3*stroke;arms[1].pivot.rotation.x=-.65-.6*stroke;legs.forEach(l=>l.rotation.x=0);if(t>=1)finishDig();}else if(dwell>0){dwell-=dt;pose=dwell>3?'Checking a field measurement':'Writing in the notebook';arms[0].pivot.rotation.x=-.85;arms[1].pivot.rotation.x=dwell>3?-.35:-1.0+Math.sin(elapsed*7)*.06;legs.forEach(l=>l.rotation.x=0);root.rotation.z=Math.sin(elapsed*2)*.012;if(dwell<=0){station=(station+1)%route.length;pose='Walking';}}else{const target=route[station],dx=target.x-root.position.x,dz=target.z-root.position.z,distance=Math.hypot(dx,dz),step=Math.min(distance,dt*1.7);if(distance<.2){visits++;dwell=7;wearing=visits%2===1;outfit();}else{root.position.x+=dx/distance*step;root.position.z+=dz/distance*step;root.rotation.y=Math.atan2(dx,dz);legs.forEach((l,i)=>l.rotation.x=Math.sin(elapsed*7+i*Math.PI)*.42);arms.forEach((a,i)=>a.pivot.rotation.x=Math.sin(elapsed*7+i*Math.PI+Math.PI)*.24);root.rotation.z=0;}}
 root.position.y=heightAt(root.position.x+origin[0],origin[1]-root.position.z)-origin[2]+(digging||dwell>0?0:Math.abs(Math.sin(elapsed*7))*.04);if(follow){const delta=root.position.clone().sub(old);camera.position.add(delta);controls.target.add(delta);clearTerrain();}}
 const p=project(root.position.clone().add(new THREE.Vector3(0,2.3,0)));label.hidden=p.z< -1||p.z>1||p.x<0||p.x>host.clientWidth||p.y<0||p.y>host.clientHeight;label.style.left=p.x+'px';label.style.top=p.y+'px';status();return true;}
 function renderOverlay(renderer,camera){if(!enabled)return;const auto=renderer.autoClear;renderer.autoClear=false;renderer.clearDepth();renderer.render(overlay,camera);renderer.autoClear=auto;host.parentElement.dataset.billRenderPass='after-field-markers';}
 function screenBounds(){if(!enabled)return null;const pp=[];for(const x of [-.65,.65])for(const y of [0,2.5])for(const z of [-.65,.65])pp.push(project(root.position.clone().add(new THREE.Vector3(x,y,z))));if(pp.every(p=>p.z< -1||p.z>1))return null;const xs=pp.map(p=>p.x),ys=pp.map(p=>p.y);return {x:Math.min(...xs)-8,y:Math.min(...ys)-8,w:Math.max(...xs)-Math.min(...xs)+16,h:Math.max(...ys)-Math.min(...ys)+16};}
 return {update,releaseFollow,renderOverlay,screenBounds};
}
