import {createPits} from './pits.js';
import {createBill} from './bill.js?v=bill-pace-1';
import * as THREE from './vendor/three/three.module.js';
import {OrbitControls} from './vendor/three/OrbitControls.js';
const $=s=>document.querySelector(s);
const escapeText=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function fetchOK(url,kind='json'){const r=await fetch(url);if(!r.ok)throw Error('Could not load '+url);return r[kind]();}
export async function createScene(atlas){
 const [meta,raw,vegBuffer,lineData,featureData]=await Promise.all([fetchOK('data/3d/scene.json'),fetchOK('data/3d/terrain.f32','arrayBuffer'),fetchOK('data/3d/vegetation.u16','arrayBuffer'),fetchOK('data/3d/contours.json'),fetchOK('data/3d/features.json')]);
 const heights=new Float32Array(raw),packed=new Uint16Array(vegBuffer),origin=meta.origin_utm_e_n_z,tm=meta.terrain,host=$('#scene-canvas'),container=$('#scene-3d');
 const scene=new THREE.Scene();scene.background=new THREE.Color('#12272f');scene.fog=new THREE.Fog('#12272f',1300,3000);
 const camera=new THREE.PerspectiveCamera(43,1,.2,6000);camera.up.set(0,1,0);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#12272f');host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D terrain: drag to orbit, right drag to pan, scroll to zoom');renderer.domElement.tabIndex=0;
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=7;controls.maxDistance=1800;controls.maxPolarAngle=Math.PI*.495;controls.zoomToCursor=true;controls.autoRotateSpeed=.65;controls.listenToKeyEvents(renderer.domElement);
 scene.add(new THREE.HemisphereLight('#ffffff','#656565',2.1));const sun=new THREE.DirectionalLight('#ffffff',2);sun.position.set(-300,600,250);scene.add(sun);
 const terrainGeometry=new THREE.BufferGeometry(),positions=new Float32Array(tm.width*tm.height*3),colors=new Float32Array(positions.length),indices=[];
 const groundGray=new THREE.Color('#8b8b8b'),color=new THREE.Color();
 for(let j=0;j<tm.height;j++)for(let i=0;i<tm.width;i++){const k=j*tm.width+i,z=heights[k];positions.set([tm.x0+i*tm.step-origin[0],z-origin[2],origin[1]-(tm.y0-j*tm.step)],3*k);color.copy(groundGray);colors.set([color.r,color.g,color.b],3*k);if(i<tm.width-1&&j<tm.height-1){const a=k,b=k+1,c=k+tm.width,d=c+1;indices.push(a,c,b,b,c,d);}}
 terrainGeometry.setAttribute('position',new THREE.BufferAttribute(positions,3));terrainGeometry.setAttribute('color',new THREE.BufferAttribute(colors,3));terrainGeometry.setIndex(indices);terrainGeometry.computeVertexNormals();
 const terrain=new THREE.Mesh(terrainGeometry,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,metalness:0,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1}));scene.add(terrain);
 // Filled channels follow the same 1 m terrain facets, including cutout edges.
 const waterMeshes=new Map();
 for(const [id,info] of Object.entries(meta.water_masks||{})){
  const mask=new Uint8Array(await fetchOK(info.url,'arrayBuffer')),wi=[];
  for(let j=0;j<tm.height-1;j++)for(let i=0;i<tm.width-1;i++)if(mask[j*(tm.width-1)+i]){const a=j*tm.width+i,b=a+1,c=a+tm.width,d=c+1;wi.push(a,c,b,b,c,d);}
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setIndex(wi);
  const mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:'#68bcf0',side:THREE.DoubleSide,depthWrite:false}));mesh.position.y=.04;mesh.renderOrder=1;scene.add(mesh);waterMeshes.set(id,mesh);
 }
 const heightAt=window.AtlasTerrain.sampler(tm,heights);
 function pointFromLL(c){const [e,n]=window.proj4('EPSG:4326','+proj=utm +zone=10 +datum=NAD83 +units=m +no_defs',c.slice(0,2));return new THREE.Vector3(e-origin[0],heightAt(e,n)-origin[2],origin[1]-n);}
 // A small terrain skirt makes the crop edge legible without implying a boundary.
 const rim=[];for(let i=0;i<tm.width;i++)rim.push(i);for(let j=1;j<tm.height;j++)rim.push(j*tm.width+tm.width-1);for(let i=tm.width-2;i>=0;i--)rim.push((tm.height-1)*tm.width+i);for(let j=tm.height-2;j>=0;j--)rim.push(j*tm.width);
 const skirt=[];for(let k=0;k<rim.length;k++){const a=positions.slice(rim[k]*3,rim[k]*3+3),b=positions.slice(rim[(k+1)%rim.length]*3,rim[(k+1)%rim.length]*3+3);skirt.push(...a,a[0],-45,a[2],...b,...b,a[0],-45,a[2],b[0],-45,b[2]);}
 const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(skirt,3));sg.computeVertexNormals();scene.add(new THREE.Mesh(sg,new THREE.MeshStandardMaterial({color:'#454545',roughness:1,side:THREE.DoubleSide})));
 // Re-drape to the actual mesh facets; line height is only a 7 cm drawing clearance.
 for(const line of lineData)line.points=window.AtlasTerrain.drape(line.points,tm,origin,heightAt);
 const labeledContours=lineData.filter(l=>l.major).map(l=>({elevation:l.elevation_m,points:l.points.filter((p,i)=>i%8===0||i===l.points.length-1).map(p=>new THREE.Vector3(...p))}));
 const contourGroup=new THREE.Group();scene.add(contourGroup);
 for(const major of [false,true]){const arr=[];for(const line of lineData.filter(x=>x.major===major))for(let i=1;i<line.points.length;i++)arr.push(...line.points[i-1],...line.points[i]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));contourGroup.add(new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:major?'#424242':'#666666',transparent:true,opacity:major?.7:.33,depthWrite:false})));}
 const vp=new Float32Array(meta.vegetation.count*3),vc=new Float32Array(vp.length);const colorHeights=[0,2,7,20,65],ramp=['#c3a675','#c5bb76','#91b34e','#4d973b','#206038'].map(c=>new THREE.Color(c));
 for(let i=0;i<meta.vegetation.count;i++){const j=4*i,h=packed[j+3]/100,k=h<2?0:h<7?1:h<20?2:3,t=Math.min(1,(h-colorHeights[k])/(colorHeights[k+1]-colorHeights[k]));vp.set([packed[j]/100+meta.vegetation.offset[0]-origin[0],packed[j+2]/100+300-origin[2],origin[1]-(packed[j+1]/100+meta.vegetation.offset[1])],3*i);color.copy(ramp[k]).lerp(ramp[k+1],t);vc.set([color.r,color.g,color.b],3*i);}
 const cloudGeometry=new THREE.BufferGeometry();cloudGeometry.setAttribute('position',new THREE.BufferAttribute(vp,3));cloudGeometry.setAttribute('color',new THREE.BufferAttribute(vc,3));const cloudMaterial=new THREE.PointsMaterial({size:1.2,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.7,depthWrite:false});
 const cloud=new THREE.Points(cloudGeometry,cloudMaterial);cloud.renderOrder=2;scene.add(cloud);
 const contextGroup=new THREE.Group(),markerGroup=new THREE.Group(),boreholeGroup=new THREE.Group(),vmsGroup=new THREE.Group();scene.add(contextGroup,markerGroup,boreholeGroup,vmsGroup);let pickables=[],active=false,frame=0,lastPointer=null,lastTime=0;
 const allFeatureLookup=new Map();for(const [id,fs] of Object.entries(featureData))for(const f of fs)allFeatureLookup.set(id+':'+f.uid,f.geometry);
 function disposeGroup(g){while(g.children.length){const o=g.children[0];g.remove(o);o.geometry?.dispose();o.material?.dispose();}}
 function inBounds(v){return v.x+origin[0]>=meta.bounds_utm[0]&&v.x+origin[0]<=meta.bounds_utm[2]&&origin[1]-v.z>=meta.bounds_utm[1]&&origin[1]-v.z<=meta.bounds_utm[3];}
 const dotCanvas=document.createElement('canvas');dotCanvas.width=64;dotCanvas.height=64;const dc=dotCanvas.getContext('2d');dc.beginPath();dc.arc(32,32,27,0,Math.PI*2);dc.fillStyle='white';dc.fill();dc.strokeStyle='#243c36';dc.lineWidth=7;dc.stroke();const dotTexture=new THREE.CanvasTexture(dotCanvas);dotTexture.colorSpace=THREE.SRGBColorSpace;
 function tube(a,b,radius,col,order){const delta=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,delta.length(),10),new THREE.MeshBasicMaterial({color:col,depthTest:false,depthWrite:false}));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());m.renderOrder=order;vmsGroup.add(m);}
 function fromUTM(c){return new THREE.Vector3(c[0]-origin[0],c[2]-origin[2],origin[1]-c[1]);}
 function sync(){ $('#scene-vms').checked=atlas.state.visible.has('vms_bores');disposeGroup(vmsGroup);for(const [id,mesh] of waterMeshes)mesh.visible=atlas.state.visible.has(id);disposeGroup(markerGroup);disposeGroup(contextGroup);disposeGroup(boreholeGroup);pickables=[];contourGroup.visible=$('#contours').checked;$('#scene-contours').checked=$('#contours').checked;
  for(const id of atlas.state.visible){const d=atlas.manifest.layers.find(x=>x.id===id),arr=[],cols=[],sizes=[];for(const f of atlas.state.data.get(id).features){if(!atlas.matches(f,d))continue;const g=allFeatureLookup.get(id+':'+f.properties.uid);if(d.kind==='vms'){const p=f.properties,collar=p.trajectory_utm_e_n_z[0],dz=heightAt(collar[0],collar[1])-collar[2],anchored=c=>{const v=fromUTM(c);v.y+=dz;return v;},[a,b]=p.trajectory_utm_e_n_z.map(anchored);tube(a,b,.17,'#242737',10);tube(a,b,.09,p.color,11);for(const port of p.ports){const u=anchored(port.start_utm_e_n_z),v=anchored(port.end_utm_e_n_z);if(port.label.startsWith('G')){u.z+=.12;v.z+=.12;}tube(u,v,port.label.startsWith('G')?.045:.145,port.label.startsWith('G')?'#f1cf7b':p.color,12);}pickables.push({f,d,v:a,bottom:b});continue;}if(f.geometry.type==='Point'||f.geometry.type==='MultiPoint'){const sourceCoords=f.geometry.type==='Point'?[f.geometry.coordinates]:f.geometry.coordinates;for(let k=0;k<sourceCoords.length;k++){const xyz=g?(g.type==='Point'?g.coordinates:g.coordinates[k]):null;const v=xyz?new THREE.Vector3(...xyz):pointFromLL(sourceCoords[k]);if(!inBounds(v))continue;v.y=heightAt(v.x+origin[0],origin[1]-v.z)-origin[2];const collar=v.clone();v.y+=.08;let bottom=null;
    if(d.kind==='well'&&f.properties.total_depth_m>0&&$('#scene-wells').checked){
     const depth=f.properties.total_depth_m;bottom=collar.clone();bottom.y-=depth;
     for(const [radius,col,order] of [[.6,'#143f4d',10],[.32,'#83edff',11]]){const shaft=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,depth,8),new THREE.MeshBasicMaterial({color:col,depthTest:false,depthWrite:false}));shaft.position.copy(collar);shaft.position.y-=depth/2;shaft.renderOrder=order;boreholeGroup.add(shaft);}
     const ticks=[];for(let dep=5;dep<depth;dep+=5)ticks.push(collar.x-.8,collar.y-dep,collar.z,collar.x+.8,collar.y-dep,collar.z);
     ticks.push(bottom.x-1.3,bottom.y,bottom.z,bottom.x+1.3,bottom.y,bottom.z);
     const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.Float32BufferAttribute(ticks,3));const tick=new THREE.LineSegments(tg,new THREE.LineBasicMaterial({color:'#b3f5ff',depthTest:false,depthWrite:false}));tick.renderOrder=12;boreholeGroup.add(tick);
    }
    const st=atlas.style(f,d);color.set(st.fillColor);arr.push(...v.toArray());cols.push(color.r,color.g,color.b);pickables.push({f,d,v,bottom});}}
   else{if(waterMeshes.has(id))continue;let lines=[];const gg=g||null;if(!gg)continue;switch(gg.type){case'LineString':lines=[gg.coordinates];break;case'MultiLineString':case'Polygon':lines=gg.coordinates;break;case'MultiPolygon':lines=gg.coordinates.flat();}
    const seg=[];for(const line of lines)for(let i=1;i<line.length;i++){const a=new THREE.Vector3(...line[i-1]),b=new THREE.Vector3(...line[i]);if(!inBounds(a)||!inBounds(b))continue;const draped=window.AtlasTerrain.drape([a.toArray(),b.toArray()],tm,origin,heightAt);for(let k=1;k<draped.length;k++)seg.push(...draped[k-1],...draped[k]);}
    if(seg.length){const lg=new THREE.BufferGeometry();lg.setAttribute('position',new THREE.Float32BufferAttribute(seg,3));contextGroup.add(new THREE.LineSegments(lg,new THREE.LineBasicMaterial({color:d.color,transparent:true,opacity:.8,depthWrite:false})));}}
  }if(arr.length){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));const mat=new THREE.PointsMaterial({size:d.kind==='well'?13:d.kind==='tree'?9:8,sizeAttenuation:false,map:dotTexture,alphaTest:.2,vertexColors:true,depthTest:false,depthWrite:false});const m=new THREE.Points(geo,mat);m.renderOrder=20;markerGroup.add(m);}}
  render();
 }
 const selectGeo=new THREE.BufferGeometry();const selectMat=new THREE.PointsMaterial({color:'#ffffff',size:21,sizeAttenuation:false,map:dotTexture,alphaTest:.2,transparent:true,opacity:.65,depthTest:false,depthWrite:false});const selected=new THREE.Points(selectGeo,selectMat);selected.renderOrder=19;selected.visible=false;scene.add(selected);
 function select(f,d){const o=pickables.find(x=>x.f.properties.uid===f.properties.uid&&x.d.id===d.id);if(o){selectGeo.setAttribute('position',new THREE.Float32BufferAttribute(o.v.toArray(),3));selected.visible=true;}else selected.visible=false;render();}
 function project(v){const p=v.clone().project(camera),w=host.clientWidth,h=host.clientHeight;return{x:(p.x+1)*w/2,y:(1-p.y)*h/2,z:p.z};}
 function candidates(x,y){return pickables.map(o=>{const p=project(o.v);let distance=Math.hypot(x-p.x,y-p.y);if(o.bottom){const b=project(o.bottom),dx=b.x-p.x,dy=b.y-p.y,t=Math.max(0,Math.min(1,((x-p.x)*dx+(y-p.y)*dy)/(dx*dx+dy*dy||1)));distance=Math.min(distance,Math.hypot(x-p.x-t*dx,y-p.y-t*dy));}return{...o,distance,screen:p};}).filter(o=>o.screen.z>-1&&o.screen.z<1&&o.distance<=12).sort((a,b)=>a.distance-b.distance);}
 function choose(e){if(!lastPointer||Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y)>5)return;const r=host.getBoundingClientRect(),hits=candidates(e.clientX-r.left,e.clientY-r.top);if(hits.length){atlas.pickFeatures(hits);atlas.closeMobile();}}
 renderer.domElement.addEventListener('pointerdown',e=>{lastPointer={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',choose);
 renderer.domElement.addEventListener('pointermove',e=>{const tip=$('#scene-hover');if(e.buttons){tip.hidden=true;return;}const r=host.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,hits=candidates(x,y);tip.hidden=!hits.length;renderer.domElement.style.cursor=hits.length?'pointer':'grab';if(hits.length){tip.innerHTML=escapeText(hits[0].f.properties.label)+(hits[0].f.properties.total_depth_m?`<small>${hits[0].f.properties.total_depth_m.toFixed(2)} m total depth below ground</small>`:'')+(hits.length>1?`<small>${hits.length} nearby features · click to choose</small>`:'');tip.style.left=Math.min(x+15,host.clientWidth-300)+'px';tip.style.top=Math.max(8,y-40)+'px';}});
 renderer.domElement.addEventListener('pointerleave',()=>{$('#scene-hover').hidden=true;});
 function layoutLabels(){const box=$('#scene-labels'),w=host.clientWidth,h=host.clientHeight,br=container.getBoundingClientRect(),placed=[];const obstacles=[...document.querySelectorAll('.bill-toolbar,.scene-toolbar,.scene-legend,#scene-scale,#inspector:not([hidden])')].map(e=>{const r=e.getBoundingClientRect();return{x:r.left-br.left,y:r.top-br.top,w:r.width,h:r.height};});const intersects=(a,b)=>a.x<b.x+b.w+4&&a.x+a.w+4>b.x&&a.y<b.y+b.h+4&&a.y+a.h+4>b.y;
  const billBox=bill.screenBounds();if(billBox)obstacles.push(billBox);const pps=pickables.map(o=>({...o,p:project(o.d.kind==='vms'?o.v.clone().lerp(o.bottom,.5):o.v)})).filter(o=>o.p.z>-1&&o.p.z<1&&o.p.x>0&&o.p.x<w&&o.p.y>0&&o.p.y<h);const distance=camera.position.distanceTo(controls.target);const eligible=pps.filter(o=>o.d.kind==='vms'||o.d.kind==='well'||(o.d.kind==='tree'&&distance<150)).sort((a,b)=>({vms:3,well:2,tree:1}[b.d.kind]||0)-({vms:3,well:2,tree:1}[a.d.kind]||0));
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','scene-leaders');const nodes=[svg];for(const o of eligible){const text=o.d.kind==='vms'?o.f.properties.label:o.d.kind==='well'?o.f.properties.label+(o.bottom&&distance<450?` · ${o.f.properties.total_depth_m.toFixed(2)} m`:''):String(o.f.properties.tree_tag??''),ww=text.length*6.5+14,hh=22;if(!text)continue;let best=null;for(const gap of [12,25,40]){for(const [dx,dy] of [[gap,-hh/2],[-ww-gap,-hh/2],[-ww/2,-hh-gap],[-ww/2,gap]]){const b={x:o.p.x+dx,y:o.p.y+dy,w:ww,h:hh};if(b.x<8||b.y<8||b.x+ww>w-8||b.y+hh>h-48||[...placed,...obstacles].some(a=>intersects(a,b)))continue;if(pps.some(p=>p!==o&&p.p.x>b.x-5&&p.p.x<b.x+ww+5&&p.p.y>b.y-5&&p.p.y<b.y+hh+5))continue;best=b;break;}if(best)break;}if(!best)continue;placed.push(best);const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',o.p.x);line.setAttribute('y1',o.p.y);line.setAttribute('x2',Math.max(best.x,Math.min(o.p.x,best.x+ww)));line.setAttribute('y2',Math.max(best.y,Math.min(o.p.y,best.y+hh)));svg.append(line);const el=document.createElement('span');el.className='scene-label';el.textContent=text;el.style.cssText=`left:${best.x}px;top:${best.y}px;width:${ww}px`;nodes.push(el);}
  if(contourGroup.visible)nodes.push(...window.AtlasContourLabels.layout({lines:labeledContours,project,width:w,height:h,obstacles:[...placed,...obstacles],points:pps.map(o=>o.p),visible:v=>{
   // Hide labels behind nearer ridges; canopy returns do not hide ground annotation.
   for(let i=1;i<=48;i++){const t=i/49,e=v.x+(camera.position.x-v.x)*t+origin[0],n=origin[1]-(v.z+(camera.position.z-v.z)*t);if(e<tm.x0||e>tm.x0+(tm.width-1)*tm.step||n>tm.y0||n<tm.y0-(tm.height-1)*tm.step)continue;const y=v.y+(camera.position.y-v.y)*t+origin[2];if(heightAt(e,n)>y+.12)return false;}return true;
  }}));
  box.replaceChildren(...nodes);
  // A 50 m horizontal segment at the orbit focus, aligned with screen-right.
  const right=new THREE.Vector3(1,0,0).applyQuaternion(camera.quaternion);right.y=0;right.normalize();const a=project(controls.target),b=project(controls.target.clone().add(right.multiplyScalar(50)));const width=Math.hypot(a.x-b.x,a.y-b.y);$('#scene-scale').innerHTML=`<i style="width:${Math.min(width,w*.4)}px"></i><span>${(50*Math.min(1,w*.4/width)).toFixed(0)} m at view center</span>`;
 }
 function render(){if(!active)return;renderer.render(scene,camera);bill.renderOverlay(renderer,camera);layoutLabels();container.dataset.pointCount=String(meta.vegetation.count);container.dataset.boreholes=String(pickables.filter(x=>x.bottom&&x.d.kind==='well').length);container.dataset.vmsSleeves=String(pickables.filter(x=>x.d.kind==='vms').length);container.dataset.waterCells=String([...waterMeshes].filter(([id,m])=>m.visible).reduce((n,[id])=>n+meta.water_masks[id].filled_cells,0));container.dataset.camera=camera.position.toArray().map(x=>x.toFixed(1)).join(',');}
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);render();}
 function animate(time){if(!active)return;const dt=Math.min(.05,(time-lastTime)/1000||.016);lastTime=time;if(!bill.dragging)controls.update(dt);if(bill.update(dt))render();frame=requestAnimationFrame(animate);}
 controls.addEventListener('change',render);new ResizeObserver(resize).observe(host);
 function centerFor(name){if(name==='trees')return new THREE.Vector3(15,heightAt(444815,4397850)-origin[2],0);return new THREE.Vector3(0,heightAt(444800,4397850)-origin[2],0);}
 function preset(name='site'){if(!active)return;bill.cancelCarry();bill.releaseFollow();const c=centerFor(name),distance=name==='trees'?140:name==='landscape'?650:370;controls.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(distance*.6,distance*.7,distance*.65));controls.update();render();}
 function focus(f,d){bill.cancelCarry();bill.releaseFollow();const p=pickables.find(x=>x.f.properties.uid===f.properties.uid&&x.d.id===d.id);if(!p)return;const target=p.d.kind==='vms'?p.v.clone().lerp(p.bottom,.5):p.v;controls.target.copy(target);camera.position.copy(target).add(p.d.kind==='vms'?new THREE.Vector3(18,18,25):new THREE.Vector3(45,60,55));controls.update();select(f,d);}
 const stations=atlas.state.data.get('wells').features.filter(f=>['Well 6','Well 7','Well 10','Well 5'].includes(f.properties.label)).map(f=>{const v=pointFromLL(f.geometry.coordinates);return {x:v.x,z:v.z,label:f.properties.label};});
 const pits=createPits({scene,terrain,heightAt,origin,container});
 // Hit only the ground mesh: canopy and subsurface infrastructure never capture a drop.
 const groundRay=new THREE.Raycaster(),groundPointer=new THREE.Vector2();
 function pickGround(clientX,clientY){const r=host.getBoundingClientRect();if(clientX<r.left||clientX>r.right||clientY<r.top||clientY>r.bottom)return null;groundPointer.set((clientX-r.left)/r.width*2-1,1-(clientY-r.top)/r.height*2);groundRay.setFromCamera(groundPointer,camera);const hit=groundRay.intersectObject(terrain,false)[0];if(!hit)return null;const p=hit.point.clone();p.y=heightAt(p.x+origin[0],origin[1]-p.z)-origin[2];return p;}
 const bill=createBill({scene,pits,pickGround,heightAt,origin,camera,controls,project,host,render,stations,explore:()=>preset()});
 const billBar=$('#bill-toolbar');new ResizeObserver(()=>{container.style.setProperty('--bill-toolbar-height',billBar.getBoundingClientRect().height+'px');render();}).observe(billBar);
 $('#scene-vms').onchange=e=>atlas.setVisible('vms_bores',e.target.checked);$('#scene-vms-detail').onclick=()=>{atlas.setVisible('vms_bores',true);controls.autoRotate=false;$('#scene-spin').setAttribute('aria-pressed','false');const p=pickables.find(x=>x.d.kind==='vms');if(p)focus(p.f,p.d);atlas.closeMobile();};
 $('#scene-controls').hidden=innerWidth<=760;$('#scene-controls-toggle').setAttribute('aria-expanded',String(innerWidth>760));$('#scene-controls-toggle').onclick=()=>{const el=$('#scene-controls');el.hidden=!el.hidden;$('#scene-controls-toggle').setAttribute('aria-expanded',String(!el.hidden));render();};
 $('#scene-contours').onchange=e=>{$('#contours').checked=e.target.checked;$('#contours').dispatchEvent(new Event('change'));sync();};
 $('#scene-home').onclick=()=>{controls.autoRotate=false;$('#scene-spin').setAttribute('aria-pressed','false');preset();};$('#scene-top').onclick=()=>{controls.autoRotate=false;$('#scene-spin').setAttribute('aria-pressed','false');const distance=Math.max(100,camera.position.distanceTo(controls.target));camera.position.copy(controls.target).add(new THREE.Vector3(0,distance,.01));controls.update();};$('#scene-spin').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('#scene-spin').setAttribute('aria-pressed',String(controls.autoRotate));};$('#scene-wells').onchange=sync;$('#scene-veg').onchange=e=>{cloud.visible=e.target.checked;render();};$('#scene-opacity').oninput=e=>{cloudMaterial.opacity=Number(e.target.value);render();};$('#scene-size').oninput=e=>{cloudMaterial.size=Number(e.target.value);render();};
 sync();
 return {get active(){return active;},meta,open(){active=true;container.hidden=false;$('.map-shell').classList.add('is-3d');$('#toggle-3d').textContent='Back to map';$('#toggle-3d').setAttribute('aria-pressed','true');atlas.closeMobile();$('#map-message').hidden=true;sync();resize();preset();if(atlas.state.selected)select(atlas.state.selected.f,atlas.state.selected.d);lastTime=0;frame=requestAnimationFrame(animate);},close(){bill.cancelCarry();active=false;cancelAnimationFrame(frame);container.hidden=true;$('.map-shell').classList.remove('is-3d');$('#toggle-3d').textContent='3D hillslope';$('#toggle-3d').setAttribute('aria-pressed','false');atlas.map.invalidateSize();window.scheduleLabels?.();},sync,select,clearSelection(){selected.visible=false;render();},focus,preset};
}
